version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=vendingmachinepassword
      - POSTGRES_USER=vendingmachine
      - POSTGRES_DB=vendingmachine
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
